import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Financial, Tax, and Legal Disclaimer (Canada) | CrewBooks",
  description: "CrewBooks disclaimer: record-keeping and organizational tool only; not tax, accounting, legal, or financial advice.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <Card className="w-full max-w-2xl">
        <CardHeader>
          <div className="flex items-center gap-2 mb-2">
            <Button variant="ghost" size="sm" asChild>
              <Link href="/signup">
                <ArrowLeft className="h-4 w-4" />
              </Link>
            </Button>
            <CardTitle className="text-xl">Financial, Tax, and Legal Disclaimer (Canada)</CardTitle>
          </div>
        </CardHeader>
        <CardContent className="space-y-4 text-sm text-muted-foreground">
          <p>
            This application is provided solely as a record-keeping and organizational tool. It is intended to assist users in storing documents, tracking income and expenses, recording vehicle mileage, and organizing financial information for personal reference.
          </p>
          <p>
            This application does not provide tax advice, accounting advice, legal advice, or financial advice. Any calculations, categorizations, summaries, estimates, or reports generated by the application are for informational purposes only and may not reflect your actual tax obligations, allowable deductions, or financial position.
          </p>
          <p>
            Tax laws, regulations, reporting requirements, and administrative policies—including those of the Canada Revenue Agency (CRA)—vary based on individual circumstances and may change over time. The application does not determine eligibility for deductions, credits, capital cost allowance (CCA), mileage claims, employment or self-employment classifications, or any other tax treatment.
          </p>
          <p>
            This application does not replace or replicate official CRA records and does not guarantee acceptance of any information by the Canada Revenue Agency or any other authority.
          </p>
          <p>You are solely responsible for:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>maintaining accurate and complete records,</li>
            <li>ensuring compliance with all applicable federal, provincial, and local laws and regulations,</li>
            <li>determining how information stored in the application is used when preparing tax filings or financial reports, and</li>
            <li>verifying all information prior to submission to the CRA or any other authority.</li>
          </ul>
          <p>
            You should consult a qualified Canadian accountant, tax professional, or legal advisor before filing taxes or making financial decisions based on information stored in this application.
          </p>
          <p>
            To the maximum extent permitted by law, the developers and operators of this application disclaim all liability for errors, omissions, inaccuracies, penalties, audits, reassessments, interest, or other financial or legal consequences arising from the use of this application.
          </p>
          <p>
            By creating an account or using this application, you acknowledge that you have read, understood, and agreed to this disclaimer.
          </p>
          <div className="pt-4">
            <Button variant="outline" asChild>
              <Link href="/signup">Back to Sign Up</Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
